# This is a basic workflow to help you get started with Actions

name: Publish presentations

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish"
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Specifying permissions
    permissions:
      contents: read      # to checkout code
      pages: write        # to publish to GitHub Pages
      id-token: write     # required for OIDC authentication

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Build Markdown index
        run: |
          # find all .md files (case-insensitive), exclude README.md, sort
          mapfile -t files < <(git ls-files -z | tr '\0' '\n' | grep -i '\.md$' | grep -vi '^readme\.md$' | sort)
          # build index content
          {
            echo "# Index"
            echo
            for f in "${files[@]}"; do
              # skip the generated index itself if present
              [[ "$(basename "$f")" =~ ^index\.md$ ]] && continue
              # convert .md -> .html for link target, escape spaces
              target="${f%.[mM][dD]}.html"
              # use relative path text and HTML target
              echo "- [${f}](${target})"
            done
          } > ./_site/index.md
        shell: bash

      - name: Convert to HTML
        uses: KoharaKazuya/marp-cli-action@v4
        with:
          generate-html: true
          generate-pdf: false
          generate-pptx: false

      - name: debug
        run: ls -la

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
